def libs():
    dicts = {"person": "человек",
             "bicycle": "велосипед",
             "car": "автомобиль",
             "motorcycle": "мотоцикл",
             "airplane": "самолет",
             "bus": "автобус",
             "train": "поезд",
             "truck": "грузовик",
             "boat": "катер",
             "traffic light": "светофор",
             "fire hydrant": "пожарный гидрант",
             "stop sign": "стоп",
             "parking meter": "паркомат",
             "bench": "скамейка",
             "bird": "птица",
             "cat": "кошка",
             "dog": "собака",
             "horse": "лошадь",
             "sheep": "овца",
             "cow": "корова",
             "elephant": "слон",
             "bear": "медведь",
             "zebra": "зебра",
             "giraffe": "жираф",
             "backpack": "рюкзак",
             "umbrella": "зонт",
             "handbag": "сумочка",
             "tie": "галстук",
             "suitcase": "чемодан",
             "frisbee": "фрисби",
             "skis": "лыжи",
             "snowboard": "сноуборд",
             "sports ball": "спортивный мяч",
             "kite": "воздушный змей",
             "baseball bat": "бейсбольная бита",
             "baseball glove": "бейсбольная перчатка",
             "skateboard": "скейтборд",
             "surfboard": "доска для серфинга",
             "tennis racket": "теннисная ракетка",
             "bottle": "бутылка",
             "wine glass": "бокал",
             "cup": "чашка",
             "fork": "вилка",
             "knife": "нож",
             "spoon": "ложка",
             "bowl": "миска",
             "banana": "банан",
             "apple": "яблоко",
             "sandwich": "бутерброд",
             "orange": "апельсин",
             "broccoli": "брокколи",
             "carrot": "морковь",
             "hot dog": "хот-дог",
             "pizza": "пицца",
             "donut": "пончик",
             "cake": "торт",
             "chair": "стул",
             "couch": "диван",
             "potted plant": "растение в горшке",
             "bed": "кровать",
             "dining table": "обеденный стол",
             "toilet": "туалет",
             "tv": "телевизор",
             "laptop": "ноутбук",
             "mouse": "мышь",
             "remote": "пульт",
             "keyboard": "клавиатура",
             "cell phone": "сотовый телефон",
             "microwave": "микроволновка",
             "oven": "духовка",
             "toaster": "тостер",
             "sink": "раковина",
             "refrigerator": "холодильник",
             "book": "книга",
             "clock": "часы",
             "vase": "ваза",
             "scissors": "ножницы",
             "teddy bear": "мишка",
             "hair dryer": "фен",
             "toothbrush": "зубная щетка"
             }
    return dicts